### ISSUE TITLE
inconsistent failure of typeahead for impersonation

### ISSUE THREAD

**Issue by brandondrew** [ucb-ist-eas/ucb_rails_user#47]
The typeahead feature is working inconsistently, leading users to believe a user is unavailable for impersonation when in fact that user is available.  

1. go to https://portal.berkeley.edu/admin/impersonations
2. and type in "Jaime" (not "Jamie") you will not see any names in the typeahead list
3. if you type "James" you will see names (so there is no problem with just a single name of 5 characters)
4. if you type "Jaime M" you will see Jaime Martin and Jaime Martinez (so there are people matching "Jaime")

**Comment by darinwilson** [comment]
This doesn't seem to be an issue anymore - closing.
